/*
Enter your query here.
*/
SELECT (CASE GRADES.grade >= 8 WHEN TRUE THEN STUDENTS.name ELSE NULL END), GRADES.grade, STUDENTS.marks FROM STUDENTS
    INNER JOIN GRADES ON STUDENTS.MARKS BETWEEN min_mark AND max_mark
    ORDER BY GRADES.grade DESC, STUDENTS.name, STUDENTS.marks;
