/*
Enter your query here.
*/
SET sql_mode = '';
SELECT CO.CONTEST_ID, CO.HACKER_ID, CO.NAME, SUM(TOTAL_SUBMISSIONS), SUM(TOTAL_ACCEPTED_SUBMISSIONS), SUM(TOTAL_VIEWS), SUM(TOTAL_UNIQUE_VIEWS) FROM CONTESTS CO
    JOIN COLLEGES COL
        ON CO.CONTEST_ID = COL.CONTEST_ID
        
    JOIN CHALLENGES CH
        ON COL.COLLEGE_ID = CH.COLLEGE_ID
        
    LEFT JOIN (SELECT CHALLENGE_ID, SUM(TOTAL_VIEWS) AS TOTAL_VIEWS, SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS FROM VIEW_STATS 
               GROUP BY CHALLENGE_ID) VS
        ON CH.CHALLENGE_ID = VS.CHALLENGE_ID
        
    LEFT JOIN (SELECT CHALLENGE_ID, SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS FROM SUBMISSION_STATS
               GROUP BY CHALLENGE_ID) SS
        ON CH.CHALLENGE_ID = SS.CHALLENGE_ID
        
    GROUP BY CO.CONTEST_ID, CO.HACKER_ID
    HAVING SUM(TOTAL_SUBMISSIONS) != 0 OR
           SUM(TOTAL_ACCEPTED_SUBMISSIONS) != 0 OR
           SUM(TOTAL_VIEWS) != 0 OR
           SUM(TOTAL_UNIQUE_VIEWS) != 0
    ORDER BY CONTEST_ID
;